name: Create Project Repository

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the new project repository'
        required: true

jobs:
  create_project_repository:
    runs-on: ubuntu-latest
    steps:
       - name: Create Repository from Template
         run: |
           gh repo create "${{ github.event.inputs.project_name }}" --template="${{ vars.TEMPLATE_REPO }}" --private --include-all-branches
         env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}


