name: Create Project Repository

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the new project repository'
        required: true

jobs:
  create_project_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Create Repository from Template
        run: |
          PROJECT_NAME="${{ github.event.inputs.project_name }}"
          TEMPLATE_REPO="${{ secrets.TEMPLATE_REPO }}"
          gh repo create "$PROJECT_NAME" -p $TEMPLATE_REPO --include-all-branches --private
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
