name: Create Project Repository

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the new project repository'
        required: true

jobs:
  create_project_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Create Repository from Template
        run: |
          gh repo create "${{ github.event.inputs.project_name }}" --template="${{ vars.TEMPLATE_REPO }}" --private --include-all-branches
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Protect Main Branch
        if: ${{ success() }}
        run: |
          gh api repos/${{ github.event.inputs.project_name }}/branches/main/protection/rules \
              --input <(echo '{"pattern":"main","requires_approving_reviews":true,"required_approving_review_count":1,"required_pull_request_reviews":{"dismiss_stale_reviews":false,"require_code_owner_reviews":false},"restrictions":{"users":[],"teams":[]}}')
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}